# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: daily-test

on:
  schedule:
    - cron: '0 8 * * *'

jobs:
  test:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: dev
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade wheel
        if [ -f requirements-dev-osx.txt ]; then pip install -r requirements-dev-osx.txt; fi
    - name: Test
      run: |
        source ./tests/daily_test.sh
    - name: Upload test result
      uses: SamKirkland/FTP-Deploy-Action@4.3.2
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./tests/
        server-dir: ./app/tests/
        exclude: |
          assets/**
          *.py
          *.sh
